name: C/C++ CI for win

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: make build space
      run: mkdir build
    - name: install conan
      run: |
            REM We use this source (temporarily?) until choco has updated their version of conan
            REM choco install conan -y -s="https://api.bintray.com/nuget/anotherfoxguy/choco-pkg"
            pip install conan
      shell: cmd
    - name: configure
      run: |
          env
          cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_PROGRAM_PATH="%programfiles%\Conan\conan" ..
      shell: cmd
      working-directory: build
    - name: build
      run: cmake --build .
      working-directory: build

# for windows build https://github.com/Chatterino/chatterino2/blob/master/.github/workflows/build.yml

